version: '3'

services:
  bot:
    container_name: bot
    build:
      context: ./
      dockerfile: Dockerfile
    restart: always
    environment:
      NODE_ENV: production
    depends_on:
      - db
    env_file:
      - .env

  db:
    image: mysql
    container_name: database
    restart: always
    env_file:
      - .env
    ports:
      - '3306:3306'

